# Generated by Django 6.0.4 on 2026-04-24 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('temporary', 'временный'), ('permanent', 'бессрочный')], max_length=20, verbose_name='тип_доступа')),
                ('start_date', models.DateField(verbose_name='дата_начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='дата_окончания')),
                ('status', models.CharField(choices=[('active', 'активен'), ('inactive', 'неактивен')], max_length=10, verbose_name='статус')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Доступ',
                'verbose_name_plural': 'Доступы',
            },
        ),
    ]
